apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - ../../base/prometheus/
#  - cloudflare.yaml
#  - cloudflare-secret.yaml
#  - linkding-container-env-secret.yaml
