apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets
  namespace: vault-secrets-operator-system
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "0.29.1"
      sourceRef:
        kind: HelmRepository
        name: vault-secrets
        namespace: vault-secrets-operator-system
      interval: 5m 
  values:
    installCRDs: true
