apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault-secrets
  namespace: vault-secrets-operator-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
